############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2014 Xilinx Inc. All rights reserved.
############################################################
#config_interface -register_io scalar_all
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ax_left_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ax_left_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ax_left_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ax_left_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ax_left_add2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ax_left_add3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ax_left
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ay_left_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ay_left_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Ay_left_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ay_left_add2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ay_left_add3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Ay_left
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Az_left_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Az_left_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Az_left_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Az_left
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Bx_right_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Bx_right_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Bx_right_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bx_right_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bx_right_add2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bx_right_add3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bx_right
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" By_right_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" By_right_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" By_right_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" By_right_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" By_right_add3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" By_right
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Bz_right_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Bz_right_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bz_right_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Bz_right
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Dx
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Dx2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Dy
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Dy2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Dz
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Dz2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Dd_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" Dd_add2
set_directive_resource -core FRSqrt_nodsp "calc_lateral_gradients" dist
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdAx
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdAy
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdAz
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_X_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_X_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dA_X_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_Y_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_Y_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dA_Y_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_Z_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dA_Z_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dA_Z_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdx_A_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdx_A_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdx_A
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_A_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_A_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_A_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdteta_A_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdteta_A
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_X_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_X_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dB_X_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_Y_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_Y_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dB_Y_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_Z_dteta_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" dB_Z_dteta_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" dB_Z_dteta
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdx_B_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdx_B_m2
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdx_B
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_B_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_B_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" drdteta_B_m3
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdteta_B_add1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" drdteta_B
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m1
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m3
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m4
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m5
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m6
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" gu_m7
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" gu_a1
set_directive_resource -core FAddSub_nodsp "calc_lateral_gradients" gu_a2
set_directive_resource -core FExp_nodsp "calc_lateral_gradients" gu_exp1
set_directive_resource -core FExp_nodsp "calc_lateral_gradients" gu_exp2
set_directive_resource -core Fmul_nodsp "calc_lateral_gradients" Grad_U_tmp
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_x_a1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_x_a2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" r_long_x_m1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_x
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_y_a1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_y_a2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" r_long_y_m1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_y
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" r_long_x2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" r_long_y2
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" r_long_a1
set_directive_resource -core FRSqrt_nodsp "calc_longitudal_gradiets" r_long
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp1_m1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" tmp1_a1
set_directive_resource -core FExp_nodsp "calc_longitudal_gradiets" tmp1_exp1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp1_m2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp2_m1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp2_m2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp2_m3
set_directive_resource -core FExp_nodsp "calc_longitudal_gradiets" tmp2_exp1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" tmp2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" dUdr_C_1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" dUdr_C_2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" dUdr_C_3
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" dUdr_C_2_m1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" dUdr_C_3_m1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" dUdr_C_2_a1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" dUdr_C_3_a1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" Grad_tmp_y
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" Grad_tmp_x
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_1_m1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_1_m2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_1_m3
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_1_m4
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" GradU_C_teta_1_a1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_3_m1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_3_m2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_3_m3
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_3_m4
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" GradU_C_teta_3_a1
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" GradU_C_teta_3
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" Grad_tmp_a1
set_directive_resource -core FAddSub_nodsp "calc_longitudal_gradiets" Grad_tmp_a2
set_directive_resource -core Fmul_nodsp "calc_longitudal_gradiets" Grad_tmp
